---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-dra-driver-role-binding
  namespace: {{ include "k8s-dra-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: nvidia-dra-driver-service-account
  namespace: {{ include "k8s-dra-driver.namespace" . }}
roleRef:
  kind: ClusterRole
  name: nvidia-dra-driver-role
  apiGroup: rbac.authorization.k8s.io
