---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-dra-driver-role-binding
  namespace: nvidia-dra-driver
subjects:
- kind: ServiceAccount
  name: nvidia-dra-driver-service-account
  namespace: nvidia-dra-driver
roleRef:
  kind: ClusterRole
  name: nvidia-dra-driver-role
  apiGroup: rbac.authorization.k8s.io
