---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-dra-driver.fullname" . }}-controller
  namespace: {{ include "k8s-dra-driver.namespace" . }}
  labels:
    {{- include "k8s-dra-driver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-dra-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-dra-driver.templateLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-dra-driver.serviceAccountName" . }}
      nodeSelector:
        nvidia.com/dra.controller: "true"
      containers:
      - name: controller
        image: {{ include "k8s-dra-driver.fullimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["nvidia-dra-controller", "-v", "6"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
