---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .MpsControlDaemonNamespace }}
  name: {{ .MpsControlDaemonName }}
  labels:
    app: {{ .MpsControlDaemonName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .MpsControlDaemonName }}
  template:
    metadata:
      labels:
        app: {{ .MpsControlDaemonName }}
    spec:
      nodeName: {{ .NodeName }}
      containers:
      - name: mps-control-daemon
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command:
        - "chroot"
        - "/driver-root"
        - "nvidia-cuda-mps-control"
        - "-f"
        startupProbe:
          exec:
            command:
            - "ls"
            - "/driver-root/tmp/nvidia-mps/control"
          initialDelaySeconds: 1
          periodSeconds: 1
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "{{ .CUDA_VISIBLE_DEVICES }}"
		{{- if .CUDA_MPS_ACTIVE_THREAD_PERCENTAGE }}
        - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
          value: "{{ .CUDA_MPS_ACTIVE_THREAD_PERCENTAGE }}"
        {{- end}}
		{{- if .CUDA_MPS_PINNED_DEVICE_MEM_LIMIT }}
        - name: CUDA_MPS_PINNED_DEVICE_MEM_LIMIT
          value: "{{ .CUDA_MPS_PINNED_DEVICE_MEM_LIMIT }}"
        {{- end}}
        volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        - name: mps-shm-directory
          mountPath: /driver-root/dev/shm
        - name: mps-pipe-directory
          mountPath: /driver-root/tmp/nvidia-mps
        - name: mps-log-directory
          mountPath: /driver-root/var/log/nvidia-mps
      volumes:
      - name: driver-root
        hostPath:
          path: {{ .NvidiaDriverRoot }}
      - name: mps-shm-directory
        hostPath:
          path: {{ .MpsShmDirectory }}
      - name: mps-pipe-directory
        hostPath:
          path: {{ .MpsPipeDirectory }}
      - name: mps-log-directory
        hostPath:
          path: {{ .MpsLogDirectory }}
